version: '3.8'

services:
  # Banco de dados MySQL
  mysql-db:
    image: mysql:8.0
    container_name: credentials-mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: 178209
      MYSQL_DATABASE: consultdg-credentials
      MYSQL_USER: credentials_user
      MYSQL_PASSWORD: credentials_pass
    ports:
      - "3306:3306"
    volumes:
      - ~/credentials/mysql-data:/var/lib/mysql
      - ~/credentials/mysql-init:/docker-entrypoint-initdb.d
    networks:
      - credentials-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10

  # Backend Spring Boot
  credentials-backend:
    build:
      context: ./credential-portals-service
      dockerfile: Dockerfile
    container_name: credentials-backend
    restart: unless-stopped
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql-db:3306/consultdg-credentials?createDatabaseIfNotExist=true&useTimezone=true&serverTimezone=UTC
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: 178209
      SPRING_DATASOURCE_DRIVER_CLASS_NAME: com.mysql.cj.jdbc.Driver
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      SPRING_JPA_SHOW_SQL: "false"
      SERVER_PORT: 8084
    ports:
      - "8084:8084"
    volumes:
      - ~/credentials/backend-logs:/app/logs
    networks:
      - credentials-network
    depends_on:
      mysql-db:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8084/actuator/health"]
      timeout: 30s
      retries: 5
      start_period: 60s

  # Frontend com Nginx
  credentials-frontend:
    image: nginx:alpine
    container_name: credentials-frontend
    restart: unless-stopped
    ports:
      - "11002:80"
    volumes:
      - ./front-credentials:/usr/share/nginx/html:ro
      - ~/credentials/nginx-conf:/etc/nginx/conf.d:ro
      - ~/credentials/nginx-logs:/var/log/nginx
    networks:
      - credentials-network
    depends_on:
      - credentials-backend
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost/"]
      timeout: 10s
      retries: 3

networks:
  credentials-network:
    driver: bridge

volumes:
  mysql-data:
    driver: local
  backend-logs:
    driver: local
  nginx-conf:
    driver: local
  nginx-logs:
    driver: local